### ISSUE TITLE
Example Issue in Data Science Prep -> Python Loops & Functions -> Looping Over Collections

### ISSUE THREAD

**Issue by Eitan8** [learn-co-curriculum/dsc-looping-over-collections#2]
Hello,

The examples used in these lessons definitely keep the learning interesting as it allows me to learn and be engaged with the content rather than just the technical tasks being executed. There is an issue though with an example brought in the first Looping Over Collections lesson. 

I kindly would request you reassess the "data" being used for countries = [...], cities = [...]. For the 8th country listed, Israel, the associated capital "Tel Aviv" is inaccurate. The capital of Israel is Jerusalem.

Happy to discuss further.
 

Thanks,
Eitan

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by christine-egan42** [comment]
merged old edits, fixed curriculum branch, updated data
